/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

/**
 *
 * @author Mauricio Herrera
 */
public class ConfirmarRegistro extends javax.swing.JDialog {

    /**
     * Creates new form ConfirmarRegistro
     *
     * @param parent
     * @param modal
     */
    public ConfirmarRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkImportante = new javax.swing.JCheckBox();
        btnConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lbltipolibro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTipoPasta = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkImportante.setText("Es importante");
        chkImportante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkImportante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkImportanteActionPerformed(evt);
            }
        });
        getContentPane().add(chkImportante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        btnConfirm.setText("confirmar");
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel1.setText("Titulo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTitulo.setOpaque(true);
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 300, 20));

        jLabel2.setText("Autor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, -1, -1));

        lblAutor.setBackground(new java.awt.Color(255, 255, 255));
        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAutor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAutor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAutor.setOpaque(true);
        getContentPane().add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, 300, 20));

        jLabel3.setText("Area:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblArea.setBackground(new java.awt.Color(255, 255, 255));
        lblArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblArea.setOpaque(true);
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, 20));

        jLabel4.setText("Editorial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        lblEditorial.setBackground(new java.awt.Color(255, 255, 255));
        lblEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditorial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblEditorial.setOpaque(true);
        getContentPane().add(lblEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 105, 300, 20));

        lbltipolibro.setBackground(new java.awt.Color(255, 255, 255));
        lbltipolibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltipolibro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltipolibro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbltipolibro.setOpaque(true);
        getContentPane().add(lbltipolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 300, 20));

        jLabel5.setText("Tipo libro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setText("Comentarios:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, -1, -1));

        lblComentarios.setBackground(new java.awt.Color(255, 255, 255));
        lblComentarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComentarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblComentarios.setOpaque(true);
        getContentPane().add(lblComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 305, 300, 80));

        lblPaginas.setBackground(new java.awt.Color(255, 255, 255));
        lblPaginas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPaginas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPaginas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPaginas.setOpaque(true);
        getContentPane().add(lblPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 300, 20));

        jLabel7.setText("Paginas:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setText("Tipo Pasta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, -1, -1));

        lblTipoPasta.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoPasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoPasta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoPasta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTipoPasta.setOpaque(true);
        getContentPane().add(lblTipoPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 255, 300, 20));

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFecha.setOpaque(true);
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 155, 300, 20));

        jLabel9.setText("Fecha de Compra:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, -1, -1));

        lblPais.setBackground(new java.awt.Color(255, 255, 255));
        lblPais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPais.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPais.setOpaque(true);
        getContentPane().add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 300, 20));

        jLabel10.setText("Pais:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPrecio.setOpaque(true);
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 300, 20));

        jLabel11.setText("Edicion:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, -1, -1));

        lblEdicion.setBackground(new java.awt.Color(255, 255, 255));
        lblEdicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEdicion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEdicion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblEdicion.setOpaque(true);
        getContentPane().add(lblEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 205, 300, 20));

        jLabel13.setText("Precio:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btncancel.setText("Cancelar");
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkImportanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkImportanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkImportanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmarRegistro dialog = new ConfirmarRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConfirm;
    public javax.swing.JButton btncancel;
    public javax.swing.JCheckBox chkImportante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblArea;
    public javax.swing.JLabel lblAutor;
    public javax.swing.JLabel lblComentarios;
    public javax.swing.JLabel lblEdicion;
    public javax.swing.JLabel lblEditorial;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblPaginas;
    public javax.swing.JLabel lblPais;
    public javax.swing.JLabel lblPrecio;
    public javax.swing.JLabel lblTipoPasta;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lbltipolibro;
    // End of variables declaration//GEN-END:variables

   
}
